version: '3.8'

services:
  app:
    build: .
    image: linkshortener-app
    container_name: linkshortener-app
    depends_on:
      - db
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.linkshortener.rule=Host(`short.local`)"
      - "traefik.http.routers.linkshortener.entrypoints=web"
    networks:
      - backend

  db:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_DATABASE: linkshortener
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - backend

  traefik:
    image: traefik:v2.10
    command:
      - "--api.insecure=true"
      - "--providers.file.directory=/etc/traefik"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8081:8080" # Painel Traefik
    volumes:
      - ./traefik:/etc/traefik
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - backend

volumes:
  mysql_data:

networks:
  backend:
